version: '3.9'
services:
  db:
    image: postgres:15-alpine
    restart: always
    env_file: .env
    volumes:
      - ./db:/var/lib/postgresql/data
    network_mode: host
  home-analyzer:
    volumes:
      - ./:/app
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    network_mode: host
    command: streamlit run app/main.py --server.port=8501 --server.address=0.0.0.0
